"""Build timeline.html, deliverable #4: one self-contained page, 85s
horizontal lanes (P1-P4), a marker per event, small thumbnails at each P1
shot. No external requests (thumbnails are base64 data URIs generated by
this script via ffmpeg, CSS is inline). Icons are inline SVG shapes, never
emoji, per the org's UI rule.

Usage: python build_timeline.py > ../timeline.html
(regenerates thumbnails via ffmpeg against the same WORK_DIR ref.mp4 each run)
"""
import json, os, subprocess, base64, io, html
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
census = json.load(open(os.path.join(HERE, "..", "census.json")))
REF = os.environ.get("REF_MP4")
DUR = census["source"]["duration_s"]

def thumb_b64(t):
    if not REF:
        return ""
    raw = subprocess.run(["ffmpeg", "-v", "error", "-ss", f"{t:.3f}", "-i", REF,
                           "-frames:v", "1", "-vf", "scale=90:-1",
                           "-f", "image2pipe", "-vcodec", "png", "-"],
                          capture_output=True).stdout
    im = Image.open(io.BytesIO(raw)).convert("RGB")
    buf = io.BytesIO()
    im.save(buf, format="JPEG", quality=55)
    return base64.b64encode(buf.getvalue()).decode()

def pct(t):
    return t / DUR * 100

ICON_FOCUS = '<svg viewBox="0 0 16 16" width="10" height="10"><circle cx="8" cy="8" r="6" fill="currentColor"/></svg>'
ICON_TEXT = '<svg viewBox="0 0 16 16" width="10" height="10"><rect x="1" y="3" width="14" height="10" fill="none" stroke="currentColor" stroke-width="2"/></svg>'
ICON_SFX = '<svg viewBox="0 0 16 16" width="10" height="10"><polygon points="8,1 15,15 1,15" fill="currentColor"/></svg>'

PLATE_COLOR = {
    "red studio": "#5a1a1a", "real web screenshot": "#1a3a5a",
    "app UI": "#1a5a3a", "logo card": "#5a4a1a", "other": "#444",
}

shots_html = []
thumbs_html = []
for s in census["p1_shots"]:
    left, width = pct(s["t0"]), pct(s["t1"] - s["t0"])
    color = PLATE_COLOR.get(s["plate_kind"], "#444")
    label = html.escape(f"#{s['id']} {s['plate_kind']} ({s['avatar_mode']})")
    title = html.escape(f"{s['t0']:.2f}-{s['t1']:.2f}s | {s['plate_kind']} | {s['avatar_mode']} | entry={s['entry']} exit={s['exit']} | {s['line_class']}")
    shots_html.append(
        f'<div class="shot" style="left:{left:.3f}%;width:{width:.3f}%;background:{color}" title="{title}">'
        f'<span class="shotlabel">{label}</span></div>'
    )
    tmid = (s["t0"] + s["t1"]) / 2
    b64 = thumb_b64(tmid)
    if b64:
        thumbs_html.append(
            f'<div class="thumb" style="left:{pct(tmid):.3f}%" title="{title}">'
            f'<img src="data:image/jpeg;base64,{b64}" width="45" loading="lazy" alt="frame at {tmid:.1f}s"></div>'
        )

p2_html = []
for e in census["p2_focus_events"]:
    if e["t0"] is None:
        continue
    left = pct(e["t0"])
    title = html.escape(f"{e['t0']:.2f}s {e['type']} -> {e.get('target','')}")
    p2_html.append(f'<div class="marker p2" style="left:{left:.3f}%" title="{title}">{ICON_FOCUS}</div>')

p3_html = []
for b in census["p3_text_blocks"]:
    left = pct(b["t_in"])
    w = max(pct(b["t_out"] - b["t_in"]), 0.3)
    title = html.escape(f"{b['t_in']:.2f}-{b['t_out']:.2f}s [{b['style']}] {b['text']}")
    p3_html.append(f'<div class="marker p3" style="left:{left:.3f}%;width:{w:.3f}%" title="{title}">{ICON_TEXT}</div>')

p4_html = []
for x in census["p4_sfx"]:
    left = pct(x["t"])
    title = html.escape(f"{x['t']:.2f}s {x['rough_class']} (aligned: {x['aligned_to']})")
    p4_html.append(f'<div class="marker p4" style="left:{left:.3f}%" title="{title}">{ICON_SFX}</div>')

ticks = "".join(
    f'<div class="tick" style="left:{pct(t):.3f}%"><span>{t}s</span></div>'
    for t in range(0, int(DUR) + 1, 5)
)

html_out = f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<title>BLACK LIQUIDITY reference census timeline</title>
<style>
:root {{ --ink:#07080A; --panel:#111318; --line:#2a2d35; --text:#e8e8ea; --muted:#9aa0ab; --accent:#E0202F; }}
* {{ box-sizing:border-box; }}
body {{ margin:0; background:var(--ink); color:var(--text); font:13px/1.4 -apple-system,Segoe UI,Helvetica,Arial,sans-serif; padding:16px; }}
h1 {{ font-size:16px; margin:0 0 4px; }}
p.sub {{ color:var(--muted); margin:0 0 16px; font-size:12px; }}
.timeline-wrap {{ overflow-x:auto; border:1px solid var(--line); border-radius:8px; background:var(--panel); padding:12px; }}
.timeline {{ position:relative; width:2200px; }}
.axis {{ position:relative; height:20px; border-bottom:1px solid var(--line); margin-bottom:6px; }}
.tick {{ position:absolute; top:0; height:20px; border-left:1px solid var(--line); padding-left:3px; color:var(--muted); font-size:10px; }}
.thumbrow {{ position:relative; height:80px; margin-bottom:4px; }}
.thumb {{ position:absolute; top:0; transform:translateX(-50%); }}
.thumb img {{ display:block; border:1px solid var(--line); border-radius:3px; }}
.lane {{ position:relative; height:30px; margin-bottom:4px; border-radius:4px; background:#0d0e12; }}
.lane-label {{ position:absolute; left:-58px; top:6px; width:52px; text-align:right; font-size:10px; color:var(--muted); }}
.lane-row {{ position:relative; margin-left:0; }}
.shot {{ position:absolute; top:0; bottom:0; border-right:1px solid var(--ink); overflow:hidden; }}
.shotlabel {{ position:absolute; left:3px; top:4px; font-size:9px; white-space:nowrap; color:#fff; opacity:.85; }}
.marker {{ position:absolute; top:4px; color:var(--accent); cursor:default; }}
.marker.p3 {{ height:20px; top:2px; background:rgba(224,32,47,.15); border-left:2px solid var(--accent); }}
.legend {{ margin-top:14px; display:flex; gap:18px; flex-wrap:wrap; font-size:11px; color:var(--muted); align-items:center; }}
.legend span.sw {{ display:inline-block; width:10px; height:10px; border-radius:2px; margin-right:4px; vertical-align:-1px; }}
</style></head>
<body>
<h1>BLACK LIQUIDITY reference edit — event census timeline</h1>
<p class="sub">85.24s · 1080x1920 · 30fps · @black_liquidity/7612158317695159573 — hover any marker or block for exact values. Thumbnails at each P1 shot's midpoint.</p>
<div class="timeline-wrap"><div class="timeline">
  <div class="axis">{ticks}</div>
  <div class="thumbrow">{''.join(thumbs_html)}</div>
  <div class="lane" style="height:22px"><div class="lane-label">P1 shots</div><div class="lane-row" style="position:relative;height:100%">{''.join(shots_html)}</div></div>
  <div class="lane"><div class="lane-label">P2 focus</div><div class="lane-row" style="position:relative;height:100%">{''.join(p2_html)}</div></div>
  <div class="lane"><div class="lane-label">P3 text</div><div class="lane-row" style="position:relative;height:100%">{''.join(p3_html)}</div></div>
  <div class="lane"><div class="lane-label">P4 SFX</div><div class="lane-row" style="position:relative;height:100%">{''.join(p4_html)}</div></div>
</div></div>
<div class="legend">
  <span><span class="sw" style="background:#5a1a1a"></span>red studio</span>
  <span><span class="sw" style="background:#1a3a5a"></span>real web screenshot</span>
  <span><span class="sw" style="background:#1a5a3a"></span>app UI</span>
  <span><span class="sw" style="background:#5a4a1a"></span>logo card</span>
  <span>{ICON_FOCUS} P2 focus event</span>
  <span>{ICON_TEXT} P3 text block</span>
  <span>{ICON_SFX} P4 SFX onset</span>
</div>
</body></html>
"""
print(html_out)
