"""Postgres backend for lib.db (docs/design/tasks-db-hub.md §3.1).

`lib/db.py`'s SQL is written SQLite-flavoured (`?` placeholders, `PRAGMA`,
`sqlite3.Row`, one `INSERT OR REPLACE`). This module lets that same SQL run
against Postgres 16 unchanged: a connection wrapper translates on the way
through, and a row class gives `row["col"]` + `row[0]` parity with
`sqlite3.Row`. `lib.db.get_conn()` picks this backend when `ORG_DB_URL` is
set; every call site elsewhere in the codebase is unaffected.

Importing this module is always safe even when `psycopg` is not installed —
only `connect()` requires it, and raises a clear error if it's missing.
"""
from __future__ import annotations

import re
from urllib.parse import urlsplit

try:
    import psycopg
except ImportError:  # pragma: no cover - exercised only when ORG_DB_URL is unset
    psycopg = None


class HubConnectError(RuntimeError):
    """ORG_DB_URL is set but the Postgres server could not be reached.

    Never caught to fall back to SQLite — a silent local fallback would
    recreate the split brain this backend switch removes (task brief).
    """


# Hand-written Postgres variant of lib.db.SCHEMA's *base* tables (the shape
# before lib.db._MIGRATION_COLUMNS / _C_LEVEL_SESSION_MIGRATION are applied).
# lib.db.init() runs its own ALTER TABLE ADD COLUMN loop for those on top of
# this, same as it does for a pre-migration SQLite DB — that loop is already
# plain ANSI SQL, so it needs no translation. Column names are identical to
# SCHEMA; only AUTOINCREMENT -> GENERATED ALWAYS AS IDENTITY changes.
PG_SCHEMA = """
CREATE TABLE IF NOT EXISTS tasks (
    id              TEXT PRIMARY KEY,
    project         TEXT NOT NULL,
    role            TEXT NOT NULL,
    status          TEXT NOT NULL DEFAULT 'pending',
    title           TEXT NOT NULL,
    description     TEXT NOT NULL,
    parent_task     TEXT,
    assigned_agent  TEXT,
    worktree        TEXT,
    branch          TEXT,
    depends_on      TEXT NOT NULL DEFAULT '[]',
    touches         TEXT NOT NULL DEFAULT '[]',
    report          TEXT,
    review          TEXT,
    iteration       INTEGER NOT NULL DEFAULT 0,
    session_id      TEXT,
    retry_after_ts  TEXT,
    last_checkpoint TEXT,
    owner_cto       TEXT,
    created_at      TEXT NOT NULL,
    updated_at      TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status);
CREATE INDEX IF NOT EXISTS idx_tasks_project ON tasks(project);
CREATE INDEX IF NOT EXISTS idx_tasks_role ON tasks(role);

CREATE TABLE IF NOT EXISTS events (
    -- BY DEFAULT (not ALWAYS) AS IDENTITY: scripts/migrate_tasks_db.py
    -- copies rows by primary key, events included, so it must be able to
    -- INSERT an explicit id (from the SQLite source) without the
    -- OVERRIDING SYSTEM VALUE clause ALWAYS would force on every caller.
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id     TEXT,
    actor       TEXT NOT NULL,
    kind        TEXT NOT NULL,
    payload     TEXT,
    ts          TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_events_task ON events(task_id);
CREATE INDEX IF NOT EXISTS idx_events_ts ON events(ts);

CREATE TABLE IF NOT EXISTS locks (
    key         TEXT PRIMARY KEY,
    owner       TEXT NOT NULL,
    expires_at  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS c_level_sessions (
    role             TEXT NOT NULL,
    session_id       TEXT NOT NULL,
    active_task_id   TEXT,
    spawned_at       TEXT NOT NULL,
    PRIMARY KEY (role, session_id)
);
CREATE INDEX IF NOT EXISTS idx_c_level_sessions_task
    ON c_level_sessions(active_task_id)
    WHERE active_task_id IS NOT NULL;
"""


# ---------------------------------------------------------------------------
# sqlite3.Row parity
# ---------------------------------------------------------------------------

class Row:
    """Mapping + sequence, like sqlite3.Row: row["col"] and row[0] both work.

    Also satisfies Python's dict() mapping protocol (keys() + __getitem__),
    so `dict(row)` works exactly as it does for a real sqlite3.Row — lib.db
    relies on that in get_task/list_tasks/recent_events/find_conflicts.
    """
    __slots__ = ("_map", "_values")

    def __init__(self, columns: list[str], values: tuple):
        self._map = dict(zip(columns, values))
        self._values = tuple(values)

    def __getitem__(self, key):
        if isinstance(key, int):
            return self._values[key]
        return self._map[key]

    def keys(self):
        return list(self._map.keys())

    def get(self, key, default=None):
        return self._map.get(key, default)

    def __iter__(self):
        return iter(self._values)

    def __len__(self):
        return len(self._values)

    def __eq__(self, other):
        if isinstance(other, Row):
            return self._map == other._map
        return NotImplemented

    def __repr__(self):  # pragma: no cover - debugging aid only
        return f"db_pg.Row({self._map!r})"


class _EmptyCursor:
    """Result of a no-op PRAGMA (journal_mode, foreign_keys, ...)."""
    rowcount = 0

    def fetchone(self):
        return None

    def fetchall(self):
        return []

    def __iter__(self):
        return iter(())


# ---------------------------------------------------------------------------
# SQL translation
# ---------------------------------------------------------------------------

_PRAGMA_TABLE_INFO_RE = re.compile(r"PRAGMA\s+table_info\((\w+)\)", re.IGNORECASE)
_PRAGMA_RE = re.compile(r"^\s*PRAGMA\b", re.IGNORECASE)

# table -> primary-key column(s), for the one INSERT OR REPLACE call site
# (lib.db.acquire_lock, into `locks`). A map (not a one-off string swap) so a
# second call site on an unmapped table fails loudly instead of emitting SQL
# that silently does the wrong thing.
_UPSERT_PK = {"locks": ("key",)}

_INSERT_OR_REPLACE_RE = re.compile(
    r"^\s*INSERT\s+OR\s+REPLACE\s+INTO\s+(\w+)\s*\(([^)]+)\)\s*VALUES\s*\(([^)]+)\)\s*$",
    re.IGNORECASE,
)


def _rewrite_insert_or_replace(sql: str) -> str:
    m = _INSERT_OR_REPLACE_RE.match(sql)
    if not m:
        return sql
    table, cols_raw, vals_raw = m.groups()
    cols = [c.strip() for c in cols_raw.split(",")]
    pk = _UPSERT_PK.get(table)
    if pk is None:
        raise ValueError(
            f"INSERT OR REPLACE INTO {table}: no primary-key entry in "
            f"lib.db_pg._UPSERT_PK -- add one before running this on Postgres"
        )
    updates = ", ".join(f"{c} = EXCLUDED.{c}" for c in cols if c not in pk)
    return (
        f"INSERT INTO {table} ({cols_raw}) VALUES ({vals_raw}) "
        f"ON CONFLICT ({', '.join(pk)}) DO UPDATE SET {updates}"
    )


def _split_statements(script: str) -> list[str]:
    """executescript's SQLite semantics: run each `;`-terminated statement in
    turn. Safe for the controlled DDL/backfill text this is actually called
    with (lib.db.SCHEMA-shaped scripts) — no semicolons inside comments or
    string literals there."""
    return [s.strip() for s in script.split(";") if s.strip()]


def _translate(sql: str):
    """Return None for a no-op PRAGMA, else the Postgres-ready SQL text.

    PRAGMA table_info(<table>) is translated (not no-op'd) into a real
    information_schema query — lib.db.init()'s ALTER-TABLE-ADD-COLUMN loop
    reads its result to stay idempotent, so it can't become inert. Every
    other PRAGMA (journal_mode, foreign_keys) is a true SQLite-only no-op.
    """
    stripped = sql.strip()
    m = _PRAGMA_TABLE_INFO_RE.search(stripped)
    if m:
        table = m.group(1)
        return (
            "SELECT column_name AS name FROM information_schema.columns "
            f"WHERE table_name = '{table}' ORDER BY ordinal_position"
        )
    if _PRAGMA_RE.match(stripped):
        return None
    return _rewrite_insert_or_replace(stripped).replace("?", "%s")


# ---------------------------------------------------------------------------
# connection / cursor wrappers
# ---------------------------------------------------------------------------

class Cursor:
    def __init__(self, cur):
        self._cur = cur

    @property
    def rowcount(self):
        return self._cur.rowcount

    def _columns(self) -> list[str]:
        return [d[0] for d in (self._cur.description or [])]

    def fetchone(self):
        row = self._cur.fetchone()
        if row is None:
            return None
        return Row(self._columns(), row)

    def fetchall(self):
        cols = self._columns()
        return [Row(cols, r) for r in self._cur.fetchall()]

    def __iter__(self):
        cols = self._columns()
        for r in self._cur:
            yield Row(cols, r)


class Connection:
    """Wraps a psycopg Connection so lib.db's SQLite-flavoured SQL runs
    unchanged. Commit/rollback/close pass straight through to psycopg — the
    transactional get_conn() contract (commit on clean exit, rollback on
    exception) is unchanged by this wrapper, it just decides what SQL to
    hand psycopg."""

    def __init__(self, raw):
        self._raw = raw

    def execute(self, sql: str, params=()) -> Cursor | _EmptyCursor:
        pg_sql = _translate(sql)
        if pg_sql is None:
            return _EmptyCursor()
        cur = self._raw.cursor()
        cur.execute(pg_sql, tuple(params) if params else None)
        return Cursor(cur)

    def executemany(self, sql: str, seq_of_params) -> Cursor:
        pg_sql = _translate(sql)
        cur = self._raw.cursor()
        cur.executemany(pg_sql, [tuple(p) for p in seq_of_params])
        return Cursor(cur)

    def executescript(self, script: str) -> None:
        for stmt in _split_statements(script):
            self.execute(stmt)

    def commit(self):
        self._raw.commit()

    def rollback(self):
        self._raw.rollback()

    def close(self):
        self._raw.close()

    def cursor(self):
        return Cursor(self._raw.cursor())


def _host_from_url(url: str) -> str:
    try:
        parts = urlsplit(url)
        return f"{parts.hostname}:{parts.port or 5432}"
    except Exception:  # pragma: no cover - defensive only
        return "?"


def connect(url: str, timeout: float | None = None) -> Connection:
    """Open a Postgres connection for `url`. Raises HubConnectError (never
    falls back to SQLite) if psycopg is missing or the server can't be
    reached within `timeout` seconds (default 10)."""
    if psycopg is None:
        raise HubConnectError(
            "ORG_DB_URL is set but the 'psycopg' package is not installed "
            "-- pip install 'psycopg[binary]' (see requirements.txt)"
        )
    host = _host_from_url(url)
    try:
        raw = psycopg.connect(url, autocommit=False,
                               connect_timeout=timeout or 10)
    except Exception as exc:
        raise HubConnectError(
            f"ORG_DB_URL points at {host} but it is unreachable: {exc}"
        ) from exc
    return Connection(raw)
