"""Postgres backend for lib.db (docs/design/tasks-db-hub.md §3.1).

`lib/db.py`'s SQL is written SQLite-flavoured (`?` placeholders, `PRAGMA`,
`sqlite3.Row`, one `INSERT OR REPLACE`). This module lets that same SQL run
against Postgres 16 unchanged: a connection wrapper translates on the way
through, and a row class gives `row["col"]` + `row[0]` parity with
`sqlite3.Row`. `lib.db.get_conn()` picks this backend when `ORG_DB_URL` is
set; every call site elsewhere in the codebase is unaffected.

Importing this module is always safe even when `psycopg` is not installed —
only `connect()` requires it, and raises a clear error if it's missing.
"""
from __future__ import annotations

import re
import threading
from urllib.parse import urlsplit

try:
    import psycopg
except ImportError:  # pragma: no cover - exercised only when ORG_DB_URL is unset
    psycopg = None


class HubConnectError(RuntimeError):
    """ORG_DB_URL is set but the Postgres server could not be reached.

    Never caught to fall back to SQLite — a silent local fallback would
    recreate the split brain this backend switch removes (task brief).
    """


# Hand-written Postgres variant of lib.db.SCHEMA's *base* tables (the shape
# before lib.db._MIGRATION_COLUMNS / _C_LEVEL_SESSION_MIGRATION are applied).
# lib.db.init() runs its own ALTER TABLE ADD COLUMN loop for those on top of
# this, same as it does for a pre-migration SQLite DB — that loop is already
# plain ANSI SQL, so it needs no translation. Column names are identical to
# SCHEMA; only AUTOINCREMENT -> GENERATED ALWAYS AS IDENTITY changes.
PG_SCHEMA = """
CREATE TABLE IF NOT EXISTS tasks (
    id              TEXT PRIMARY KEY,
    project         TEXT NOT NULL,
    role            TEXT NOT NULL,
    status          TEXT NOT NULL DEFAULT 'pending',
    title           TEXT NOT NULL,
    description     TEXT NOT NULL,
    parent_task     TEXT,
    assigned_agent  TEXT,
    worktree        TEXT,
    branch          TEXT,
    depends_on      TEXT NOT NULL DEFAULT '[]',
    touches         TEXT NOT NULL DEFAULT '[]',
    report          TEXT,
    review          TEXT,
    iteration       INTEGER NOT NULL DEFAULT 0,
    session_id      TEXT,
    retry_after_ts  TEXT,
    last_checkpoint TEXT,
    owner_cto       TEXT,
    created_at      TEXT NOT NULL,
    updated_at      TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status);
CREATE INDEX IF NOT EXISTS idx_tasks_project ON tasks(project);
CREATE INDEX IF NOT EXISTS idx_tasks_role ON tasks(role);

CREATE TABLE IF NOT EXISTS events (
    -- BY DEFAULT (not ALWAYS) AS IDENTITY: scripts/migrate_tasks_db.py
    -- copies rows by primary key, events included, so it must be able to
    -- INSERT an explicit id (from the SQLite source) without the
    -- OVERRIDING SYSTEM VALUE clause ALWAYS would force on every caller.
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id     TEXT,
    actor       TEXT NOT NULL,
    kind        TEXT NOT NULL,
    payload     TEXT,
    ts          TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_events_task ON events(task_id);
CREATE INDEX IF NOT EXISTS idx_events_ts ON events(ts);

CREATE TABLE IF NOT EXISTS locks (
    key         TEXT PRIMARY KEY,
    owner       TEXT NOT NULL,
    expires_at  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS c_level_sessions (
    role             TEXT NOT NULL,
    session_id       TEXT NOT NULL,
    active_task_id   TEXT,
    spawned_at       TEXT NOT NULL,
    PRIMARY KEY (role, session_id)
);
CREATE INDEX IF NOT EXISTS idx_c_level_sessions_task
    ON c_level_sessions(active_task_id)
    WHERE active_task_id IS NOT NULL;

-- Org Mesh W2.1 -- Postgres mirror of lib.db.SCHEMA's hosts/letters tables.
-- Column shapes are identical; only id's AUTOINCREMENT -> IDENTITY changes,
-- same pattern as `events` above.
CREATE TABLE IF NOT EXISTS hosts (
    host         TEXT PRIMARY KEY,
    os           TEXT,
    hq_root      TEXT,
    agents_root  TEXT,
    provides     TEXT,
    max_workers  INTEGER,
    status       TEXT,
    probed_at    TEXT,
    free_gb      REAL,
    ram_free_gb  REAL,
    running      INTEGER,
    version      TEXT,
    updated_at   TEXT
);

CREATE TABLE IF NOT EXISTS letters (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    to_host       TEXT,
    to_role       TEXT,
    to_session    TEXT,
    from_role     TEXT,
    from_session  TEXT,
    body          TEXT NOT NULL,
    status        TEXT NOT NULL DEFAULT 'pending',
    created_at    TEXT,
    delivered_at  TEXT,
    attempts      INTEGER NOT NULL DEFAULT 0,
    last_error    TEXT
);
CREATE INDEX IF NOT EXISTS idx_letters_to_host_status ON letters(to_host, status);
"""


# ---------------------------------------------------------------------------
# sqlite3.Row parity
# ---------------------------------------------------------------------------

class Row:
    """Mapping + sequence, like sqlite3.Row: row["col"] and row[0] both work.

    Also satisfies Python's dict() mapping protocol (keys() + __getitem__),
    so `dict(row)` works exactly as it does for a real sqlite3.Row — lib.db
    relies on that in get_task/list_tasks/recent_events/find_conflicts.
    """
    __slots__ = ("_map", "_values")

    def __init__(self, columns: list[str], values: tuple):
        self._map = dict(zip(columns, values))
        self._values = tuple(values)

    def __getitem__(self, key):
        if isinstance(key, int):
            return self._values[key]
        return self._map[key]

    def keys(self):
        return list(self._map.keys())

    def get(self, key, default=None):
        return self._map.get(key, default)

    def __iter__(self):
        return iter(self._values)

    def __len__(self):
        return len(self._values)

    def __eq__(self, other):
        if isinstance(other, Row):
            return self._map == other._map
        return NotImplemented

    def __repr__(self):  # pragma: no cover - debugging aid only
        return f"db_pg.Row({self._map!r})"


class _EmptyCursor:
    """Result of a no-op PRAGMA (journal_mode, foreign_keys, ...)."""
    rowcount = 0

    def fetchone(self):
        return None

    def fetchall(self):
        return []

    def __iter__(self):
        return iter(())


# ---------------------------------------------------------------------------
# SQL translation
# ---------------------------------------------------------------------------

_PRAGMA_TABLE_INFO_RE = re.compile(r"PRAGMA\s+table_info\((\w+)\)", re.IGNORECASE)
_PRAGMA_RE = re.compile(r"^\s*PRAGMA\b", re.IGNORECASE)

# table -> primary-key column(s), for the one INSERT OR REPLACE call site
# (lib.db.acquire_lock, into `locks`). A map (not a one-off string swap) so a
# second call site on an unmapped table fails loudly instead of emitting SQL
# that silently does the wrong thing.
_UPSERT_PK = {"locks": ("key",)}

_INSERT_OR_REPLACE_RE = re.compile(
    r"^\s*INSERT\s+OR\s+REPLACE\s+INTO\s+(\w+)\s*\(([^)]+)\)\s*VALUES\s*\(([^)]+)\)\s*$",
    re.IGNORECASE,
)


def _rewrite_insert_or_replace(sql: str) -> str:
    m = _INSERT_OR_REPLACE_RE.match(sql)
    if not m:
        return sql
    table, cols_raw, vals_raw = m.groups()
    cols = [c.strip() for c in cols_raw.split(",")]
    pk = _UPSERT_PK.get(table)
    if pk is None:
        raise ValueError(
            f"INSERT OR REPLACE INTO {table}: no primary-key entry in "
            f"lib.db_pg._UPSERT_PK -- add one before running this on Postgres"
        )
    updates = ", ".join(f"{c} = EXCLUDED.{c}" for c in cols if c not in pk)
    return (
        f"INSERT INTO {table} ({cols_raw}) VALUES ({vals_raw}) "
        f"ON CONFLICT ({', '.join(pk)}) DO UPDATE SET {updates}"
    )


def _split_statements(script: str) -> list[str]:
    """executescript's SQLite semantics: run each `;`-terminated statement in
    turn. Safe for the controlled DDL/backfill text this is actually called
    with (lib.db.SCHEMA-shaped scripts) — no semicolons inside comments or
    string literals there."""
    return [s.strip() for s in script.split(";") if s.strip()]


def _translate_placeholders(sql: str) -> str:
    """Replace SQLite `?` placeholders with psycopg's `%s`, skipping any `?`
    that appears inside a single-quoted SQL string literal (a literal `?` in
    a value, e.g. `note = 'what?'`, must survive untouched — a blind
    str.replace("?", "%s") would corrupt it and desync the placeholder count
    from the params tuple). A doubled `''` inside a string is SQL's escaped
    quote, not the string's end."""
    out: list[str] = []
    in_string = False
    i, n = 0, len(sql)
    while i < n:
        c = sql[i]
        if in_string:
            out.append(c)
            if c == "'":
                if i + 1 < n and sql[i + 1] == "'":
                    out.append(sql[i + 1])
                    i += 2
                    continue
                in_string = False
            i += 1
            continue
        if c == "'":
            in_string = True
            out.append(c)
        elif c == "?":
            out.append("%s")
        else:
            out.append(c)
        i += 1
    return "".join(out)


def _translate(sql: str, has_params: bool = False):
    """Return None for a no-op PRAGMA, else the Postgres-ready SQL text.

    PRAGMA table_info(<table>) is translated (not no-op'd) into a real
    information_schema query — lib.db.init()'s ALTER-TABLE-ADD-COLUMN loop
    reads its result to stay idempotent, so it can't become inert. Every
    other PRAGMA (journal_mode, foreign_keys) is a true SQLite-only no-op.

    `has_params` (default False, so a no-params caller is unaffected by
    default): psycopg parses the whole query text for `%s`/`%(name)s` style
    placeholders whenever real params are supplied — a literal `%` anywhere
    in the text (including inside a quoted string, e.g. `LIKE 'a%'`) must
    then be doubled to `%%` or psycopg misreads it as a malformed
    placeholder. When no params are supplied psycopg sends the text as-is,
    so `%` must NOT be touched (a `%%` there would show up literally in the
    query). Escaping runs BEFORE the `?`-to-`%s` pass, so the `%` it inserts
    is never itself re-escaped.
    """
    stripped = sql.strip()
    m = _PRAGMA_TABLE_INFO_RE.search(stripped)
    if m:
        table = m.group(1)
        return (
            "SELECT column_name AS name FROM information_schema.columns "
            f"WHERE table_name = '{table}' ORDER BY ordinal_position"
        )
    if _PRAGMA_RE.match(stripped):
        return None
    rewritten = _rewrite_insert_or_replace(stripped)
    if has_params:
        rewritten = rewritten.replace("%", "%%")
    return _translate_placeholders(rewritten)


# ---------------------------------------------------------------------------
# connection / cursor wrappers
# ---------------------------------------------------------------------------

class Cursor:
    def __init__(self, cur):
        self._cur = cur

    @property
    def rowcount(self):
        return self._cur.rowcount

    def _columns(self) -> list[str]:
        return [d[0] for d in (self._cur.description or [])]

    def fetchone(self):
        row = self._cur.fetchone()
        if row is None:
            return None
        return Row(self._columns(), row)

    def fetchall(self):
        cols = self._columns()
        return [Row(cols, r) for r in self._cur.fetchall()]

    def __iter__(self):
        cols = self._columns()
        for r in self._cur:
            yield Row(cols, r)


class Connection:
    """Wraps a psycopg Connection so lib.db's SQLite-flavoured SQL runs
    unchanged. Commit/rollback/close pass straight through to psycopg — the
    transactional get_conn() contract (commit on clean exit, rollback on
    exception) is unchanged by this wrapper, it just decides what SQL to
    hand psycopg."""

    def __init__(self, raw):
        self._raw = raw

    def execute(self, sql: str, params=()) -> Cursor | _EmptyCursor:
        resolved = tuple(params) if params else None
        pg_sql = _translate(sql, has_params=resolved is not None)
        if pg_sql is None:
            return _EmptyCursor()
        cur = self._raw.cursor()
        cur.execute(pg_sql, resolved)
        return Cursor(cur)

    def executemany(self, sql: str, seq_of_params) -> Cursor:
        pg_sql = _translate(sql, has_params=True)
        cur = self._raw.cursor()
        cur.executemany(pg_sql, [tuple(p) for p in seq_of_params])
        return Cursor(cur)

    def executescript(self, script: str) -> None:
        for stmt in _split_statements(script):
            self.execute(stmt)

    def commit(self):
        self._raw.commit()

    def rollback(self):
        self._raw.rollback()

    def close(self):
        self._raw.close()

    def cursor(self):
        return Cursor(self._raw.cursor())

    @property
    def closed(self) -> bool:
        """Local, no-round-trip check of whether the underlying psycopg
        connection has been closed (explicitly, or by psycopg noticing a
        dead socket on a prior operation). Used by get_pooled() to decide
        whether a cached connection is still worth reusing."""
        return bool(self._raw.closed)


def _host_from_url(url: str) -> str:
    try:
        parts = urlsplit(url)
        return f"{parts.hostname}:{parts.port or 5432}"
    except Exception:  # pragma: no cover - defensive only
        return "?"


def connect(url: str, timeout: float | None = None) -> Connection:
    """Open a Postgres connection for `url`. Raises HubConnectError (never
    falls back to SQLite) if psycopg is missing or the server can't be
    reached within `timeout` seconds (default 10)."""
    if psycopg is None:
        raise HubConnectError(
            "ORG_DB_URL is set but the 'psycopg' package is not installed "
            "-- pip install 'psycopg[binary]' (see requirements.txt)"
        )
    host = _host_from_url(url)
    try:
        raw = psycopg.connect(url, autocommit=False,
                               connect_timeout=timeout or 10)
    except Exception as exc:
        raise HubConnectError(
            f"ORG_DB_URL points at {host} but it is unreachable: {exc}"
        ) from exc
    return Connection(raw)


# ---------------------------------------------------------------------------
# connection pooling (task brief gap 3): one connection per (process,
# thread, url), reused across lib.db.get_conn() calls instead of opening a
# fresh Mac->Contabo connection (~127ms round trip) for every single query.
# ---------------------------------------------------------------------------

_pool = threading.local()


def _pool_cache() -> dict:
    cache = getattr(_pool, "conns", None)
    if cache is None:
        cache = {}
        _pool.conns = cache
    return cache


def get_pooled(url: str, timeout: float | None = None) -> Connection:
    """Return this thread's cached Connection for `url`, opening one if
    there isn't a live one yet.

    Scoped by threading.local, so two threads never see each other's
    connection -- required because the MCP server runs background threads
    (delegate kickoff, _verify_claimed) alongside its main thread, and
    psycopg connections are not safe to share across threads.

    Health check is `.closed` only (no network round trip -- a round trip
    here, on every get_conn() call, would erase the latency win this pool
    exists for: a single delegate_task makes ~20 get_conn() calls). A
    connection that dies mid-use surfaces as psycopg.OperationalError from
    inside the caller's `with get_conn()` block; lib.db.get_conn() calls
    evict() in that case so the *next* acquisition opens fresh instead of
    handing back the same broken connection.
    """
    cache = _pool_cache()
    conn = cache.get(url)
    if conn is not None and not conn.closed:
        return conn
    conn = connect(url, timeout=timeout)
    cache[url] = conn
    return conn


def evict(url: str) -> None:
    """Drop and close this thread's cached connection for `url`, if any.
    Safe to call even when nothing is cached, or when the connection is
    already dead (close() errors are swallowed -- there is nothing left to
    clean up on a connection that's already gone)."""
    conn = _pool_cache().pop(url, None)
    if conn is not None:
        try:
            conn.close()
        except Exception:
            pass


def is_operational_error(exc: BaseException) -> bool:
    """True when `exc` means the psycopg connection itself is unusable
    (dropped, closed, network failure) rather than a recoverable query-level
    error a plain rollback can handle. lib.db.get_conn() uses this to decide
    eviction vs. a normal rollback-and-reuse."""
    if psycopg is None:
        return False
    return isinstance(exc, (psycopg.OperationalError, psycopg.InterfaceError))
