bst.instance.Tiramisu64.0dct="0"
bst.instance.Tiramisu64.abi_list="x86,x64,arm,arm64"
bst.instance.Tiramisu64.adb_port="5555"
bst.instance.Tiramisu64.ads_app_activity="com.uncube.gamevantage.ui.activities.MainActivity"
bst.instance.Tiramisu64.ads_app_package="com.uncube.gamevantage"
bst.instance.Tiramisu64.ads_display_time=""
bst.instance.Tiramisu64.ads_limit_min_pixels="900"
bst.instance.Tiramisu64.ads_screen_width="320"
bst.instance.Tiramisu64.ads_screen_width_percentage="20"
bst.instance.Tiramisu64.aigames_auto_collect_key_state_fps="0.0"
bst.instance.Tiramisu64.airplane_mode_active="0"
bst.instance.Tiramisu64.airplane_mode_active_time=""
bst.instance.Tiramisu64.android_google_ad_id="41501140-fbd0-4381-bafd-7256e3ba20f0"
bst.instance.Tiramisu64.android_id="26255418e4d1a0a6"
bst.instance.Tiramisu64.android_sound_while_tapping="1"
bst.instance.Tiramisu64.app_launch_count="0"
bst.instance.Tiramisu64.astc_decoding_mode="software"
bst.instance.Tiramisu64.autohide_notifications="0"
bst.instance.Tiramisu64.boot_duration="37944"
bst.instance.Tiramisu64.camera_backend=""
bst.instance.Tiramisu64.camera_device=""
bst.instance.Tiramisu64.camera_rotation_angle="0"
bst.instance.Tiramisu64.cpus="4"
bst.instance.Tiramisu64.custom_resolution_selected="0"
bst.instance.Tiramisu64.device_carrier_code="se_52099"
bst.instance.Tiramisu64.device_country_code="764"
bst.instance.Tiramisu64.device_custom_brand=""
bst.instance.Tiramisu64.device_custom_manufacturer=""
bst.instance.Tiramisu64.device_custom_model=""
bst.instance.Tiramisu64.device_profile_code="stou"
bst.instance.Tiramisu64.display_name="BlueStacks App Player 1"
bst.instance.Tiramisu64.dpi="240"
bst.instance.Tiramisu64.eco_mode_max_fps="5"
bst.instance.Tiramisu64.enable_fps_display="0"
bst.instance.Tiramisu64.enable_fullscreen_all_apps="0"
bst.instance.Tiramisu64.enable_high_fps="0"
bst.instance.Tiramisu64.enable_logcat_redirection="0"
bst.instance.Tiramisu64.enable_mobile_notifications="0"
bst.instance.Tiramisu64.enable_notifications="0"
bst.instance.Tiramisu64.enable_root_access="0"
bst.instance.Tiramisu64.enable_vsync="0"
bst.instance.Tiramisu64.fb_height="900"
bst.instance.Tiramisu64.fb_width="1600"
bst.instance.Tiramisu64.first_boot="0"
bst.instance.Tiramisu64.game_controls_enabled="1"
bst.instance.Tiramisu64.gl_win_height="889"
bst.instance.Tiramisu64.gl_win_screen="VA24G1-H"
bst.instance.Tiramisu64.gl_win_x="170"
bst.instance.Tiramisu64.gl_win_y="93"
bst.instance.Tiramisu64.google_account_logins="pass.gob1@gmail.com"
bst.instance.Tiramisu64.google_login_popup_shown="0"
bst.instance.Tiramisu64.graphics_engine="aga"
bst.instance.Tiramisu64.graphics_renderer="vlcn"
bst.instance.Tiramisu64.grm_ignored_rules=""
bst.instance.Tiramisu64.launch_date=""
bst.instance.Tiramisu64.libc_mem_allocator="jem"
bst.instance.Tiramisu64.macro_win_height="-1"
bst.instance.Tiramisu64.macro_win_screen=""
bst.instance.Tiramisu64.macro_win_x="-1"
bst.instance.Tiramisu64.macro_win_y="-1"
bst.instance.Tiramisu64.max_fps="60"
bst.instance.Tiramisu64.pin_to_top="0"
bst.instance.Tiramisu64.ram="4096"
bst.instance.Tiramisu64.show_sidebar="1"
bst.instance.Tiramisu64.split_ad_enabled="0"
bst.instance.Tiramisu64.split_ad_show_times="-1"
bst.instance.Tiramisu64.status.adb_port="5555"
bst.instance.Tiramisu64.status.ip_addr_prefix_len="24"
bst.instance.Tiramisu64.status.ip_gateway_addr="10.0.2.2"
bst.instance.Tiramisu64.status.ip_guest_addr="10.0.2.15"
bst.instance.Tiramisu64.status.session_id="1023"
bst.instance.Tiramisu64.vulkan_supported="1"
