#!/usr/bin/env python3
"""Splice generated plates/script content into the BL cut template's index.html."""
import json, sys

TEMPLATE = sys.argv[1] if len(sys.argv) > 1 else "/Users/gob/MoonieXHQ/Work/task-501f1d89/tmp/cut/index.html"
PIECES = sys.argv[2] if len(sys.argv) > 2 else "/Users/gob/MoonieXHQ/Work/task-501f1d89/tmp/cut_pieces.json"
AUDIO_MEDIA_START = float(sys.argv[3]) if len(sys.argv) > 3 else 0.0
OUT = TEMPLATE  # overwrite in place, in the cut workdir

data = json.load(open(PIECES))
src = open(TEMPLATE).read()

plates_html = "\n      ".join(data["plates"])
script_lines = "\n      ".join(data["script_lines"])
caps_js = "\n      ".join(data["caps_js"])
check_call = data["check_call"]
total_dur = data["total_dur"]

# 1) data-duration on #root
src = src.replace(
    'data-composition-id="main" data-start="0" data-duration="0"',
    f'data-composition-id="main" data-start="0" data-duration="{total_dur}"')

# 2) episode date on the brand bug (manifest created_at 2026-09-23 -> 23 ก.ย. 69)
src = src.replace('<div class="dt2">20 พ.ค. 69</div>', '<div class="dt2">23 ก.ย. 69</div>')

# 3) replace the placeholder video-track comment block + audio src with our plates
old_video_block_start = src.index("<!-- VIDEO TRACK")
old_video_block_end = src.index('<audio id="va"')
new_video_block = f"""<!-- EP57 plates, generated by tmp/build_cut.py from the beat table -->
      {plates_html}

      """
src = src[:old_video_block_start] + new_video_block + src[old_video_block_end:]

src = src.replace(
    '<audio id="va" src="media/voice.m4a" data-start="0" data-duration="0"',
    f'<audio id="va" src="media/voice.mp3" data-start="0" data-duration="{total_dur}" '
    f'data-media-start="{AUDIO_MEDIA_START}"')

# 4) insert helper functions (spotlight, credit, addCap) right after stats()
anchor = "      /* ======================== THE CUT ========================"
helpers = '''      // --- EP57 helpers: evidence spotlight, image credit, footage captions ---
      function spotlight(id, at, out, x, y, w, h) {
        var d = el('<div id="' + id + '" style="position:absolute;left:' + x + 'px;top:' + y +
          'px;width:' + w + 'px;height:' + h + 'px;border:5px solid var(--yellow);' +
          'border-radius:14px;box-shadow:0 0 24px rgba(244,223,20,.75), inset 0 0 20px rgba(244,223,20,.25);' +
          'opacity:0;transform-origin:left center"></div>');
        stage.appendChild(d);
        tl.fromTo("#" + id, { opacity: 0, scaleX: 0.3 },
          { opacity: 1, scaleX: 1, duration: 0.5, ease: E }, at);
        hide("#" + id, out - 0.1);
      }
      function credit(id, at, out, text) {
        var d = el('<div id="' + id + '" style="position:absolute;left:24px;top:24px;z-index:36;' +
          'font-family:Kanit,sans-serif;font-weight:600;font-size:22px;color:#D7DCE0;' +
          'background:rgba(7,8,10,.72);padding:6px 14px;border-radius:8px;opacity:0">' + text + '</div>');
        stage.appendChild(d);
        show("#" + id, at); hide("#" + id, out - 0.1);
      }
      var capHost = document.getElementById("caps");
      var capN = 0;
      function addCap(t0, t1, text, kind, y) {
        var id = "epcap" + (++capN);
        if (kind === "chip-comp") {
          if (y === null) { return; }  // no spot clear of both the evidence box and the avatar
          // small dark chip, positioned per-beat to clear the evidence box AND the avatar
          var d1 = el('<div class="cap" id="' + id + '" style="position:absolute;left:' +
            'var(--safe-left);right:var(--safe-right);top:' + y + 'px;font-size:38px;' +
            'background:rgba(7,8,10,.78);padding:10px 24px;border-radius:12px;' +
            'width:fit-content;margin:0 auto">' + text + '</div>');
          stage.appendChild(d1);
          tl.fromTo("#" + id, { opacity: 0, y: 14 }, { opacity: 1, y: 0, duration: 0.16, ease: "power2.out" }, t0);
          tl.to("#" + id, { opacity: 0, duration: 0.08, ease: "power1.in" }, t1 - 0.08);
          return;
        }
        // rail / chip-ff: the standing bottom caption rail. A real-footage plate
        // (rail kind) can be bright, so give it the same opaque backing .bl-legal
        // needed (text-shadow alone fails WCAG contrast over a white screenshot).
        var style = kind === "rail"
          ? "background:rgba(7,8,10,.78);padding:8px 24px;border-radius:10px;width:fit-content;margin:0 auto;left:0;right:0"
          : "";
        var d = el('<div class="cap" id="' + id + '" style="' + style + '">' + text + '</div>');
        capHost.appendChild(d);
        tl.fromTo("#" + id, { opacity: 0, y: 14 }, { opacity: 1, y: 0, duration: 0.16, ease: "power2.out" }, t0);
        tl.to("#" + id, { opacity: 0, duration: 0.08, ease: "power1.in" }, t1 - 0.08);
      }

'''
src = src.replace(anchor, helpers + anchor)

# 5) THE CUT content: replace the tl.from("#bug"...) line + generator-name comment.
# For a split-render continuation window (AUDIO_MEDIA_START > 0), the bug/logo must
# already be fully on screen at local t=0 - it is mid-episode, not entering fresh -
# so skip the slide-in entrance instead of replaying it (it visibly flickered out
# and back in at the seam when this was first tried, task-501f1d89).
old_cut_marker = 'tl.from("#bug", { x: -50, opacity: 0, duration: 0.7, ease: "power3.out" }, 0.25);'
bug_line = (old_cut_marker if AUDIO_MEDIA_START == 0.0
            else 'tl.set("#bug", { x: 0, opacity: 1 }, 0);')
new_cut = (bug_line + "\n\n      " + check_call + "\n\n      " + script_lines +
           "\n\n      " + caps_js)
src = src.replace(old_cut_marker, new_cut)

open(OUT, "w").write(src)
print("wrote", OUT, len(src), "bytes")
