# Source this from ~/.zshrc:    source /Users/gob/MoonieXHQ/Agents/Core/scripts/aliases.sh
AGENTS_ROOT="/Users/gob/MoonieXHQ/Agents/Core"

alias agents="cd $AGENTS_ROOT"
alias agents-watch="bash $AGENTS_ROOT/scripts/watch.sh"
alias agents-dash="cd $AGENTS_ROOT && python dashboard.py"
alias agents-status="cd $AGENTS_ROOT && python -m lib.db list"
alias agents-stats="cd $AGENTS_ROOT && python -m lib.db stats"
alias agents-cto="tail -F $AGENTS_ROOT/state/logs/cto.log"
alias agents-logs="ls -lt $AGENTS_ROOT/state/logs/ | head -15"
alias agents-run="cd $AGENTS_ROOT && python main.py"
alias agents-init="cd $AGENTS_ROOT && python main.py --init"
alias agents-chat="cd $AGENTS_ROOT && source .venv/bin/activate && python -m runners.cto_chat"
alias agents-spawn="bash $AGENTS_ROOT/scripts/spawn-cto.sh"
alias agents-dev-logs="bash $AGENTS_ROOT/scripts/tail-dev-logs.sh"
