#!/usr/bin/env python3
"""Render every prompt block from PROMPTS.md into the director's Sheet.

The CEO's rule is that all work goes through the Sheet, and that the operator
pastes the prompt FROM the Sheet. Until now the Sheet carried only the rules
and the element catalogue, so operators still read PROMPTS.md instead. This
generates the missing section.

It rewrites only the region between the two sentinel comments, so it is safe to
run repeatedly - re-run it after any prompt edit rather than hand-patching the
HTML, which is how the two copies drift apart.

    python3 scripts/sheet_inject_prompts.py <tracker.html>
"""
import html
import re
import sys

PROMPTS = '/Users/gob/Projects/Agents/PROMPTS.md'
BEGIN = '<!-- PROMPTS:BEGIN generated by scripts/sheet_inject_prompts.py -->'
END = '<!-- PROMPTS:END -->'

FORBIDDEN = {'@Room-Clean-Rev', '@Room-Wreck-Rev',
             '@Room-DoorOut-Down', '@Prop-Glasses'}
             # '@Motel-Walkway' unblocked 2026-08-14 (CEO replaced the
             # reference image) -- mirrors scripts/audit_prompts.py.
FROZEN_SCENES = ('4', '5', '6', '7', '8')
MAX_ELEMENTS = 10  # Seedance 2.0 cap.
MAX_ELEMENTS_SEEDANCE_25 = 50  # mirrors scripts/audit_prompts.py.
TAG = re.compile(r'@[A-Za-z][A-Za-z0-9-]*')

# Built on the Sheet's own tokens (--paper/--panel/--ink/--brass/--dnd/--line).
# The page is a deliberate single-theme dark design, so these follow it rather
# than introducing a second palette.
CSS = """
<style>
.pblock{border:1px solid var(--line-strong);border-radius:10px;margin:14px 0;
  overflow:hidden;background:var(--panel)}
.pblock-head{display:flex;flex-wrap:wrap;align-items:center;gap:8px;
  padding:10px 14px;background:var(--panel-2);border-bottom:1px solid var(--line-strong)}
.pblock-name{font-weight:600;letter-spacing:.01em;color:var(--ink)}
.pblock-count{font-variant-numeric:tabular-nums;font-size:.82em;
  color:var(--ink-faint);margin-left:auto}
.pchip{display:inline-block;font-size:.76em;padding:2px 7px;border-radius:999px;
  border:1px solid var(--line-strong);color:var(--ink-soft);white-space:nowrap}
.pchip.loc{border-color:var(--mirror);color:var(--mirror)}
.pchip.chr{border-color:var(--brass-dim);color:var(--brass)}
.pchip.prp{border-color:var(--line-strong);color:var(--ink-soft)}
.pbadge{font-size:.72em;text-transform:uppercase;letter-spacing:.06em;
  padding:2px 8px;border-radius:4px;font-weight:600}
.pbadge.frozen{background:rgba(178,58,58,.18);color:var(--dnd-bright)}
.pbadge.ok{background:rgba(201,162,39,.15);color:var(--brass)}
.pblock pre{margin:0;padding:14px;white-space:pre-wrap;word-break:break-word;
  font-size:.86em;line-height:1.55;overflow-x:auto;background:var(--paper);
  color:var(--ink)}
.pnote{padding:8px 14px;font-size:.85em;background:rgba(178,58,58,.12);
  color:var(--dnd-bright);border-bottom:1px solid var(--line-strong)}
.pcopy{font:inherit;font-size:.76em;padding:3px 10px;border-radius:5px;cursor:pointer;
  border:1px solid var(--line-strong);background:transparent;color:var(--ink-soft)}
.pcopy:hover{background:var(--panel-2);color:var(--ink)}
.pcopy:focus-visible{outline:2px solid var(--brass);outline-offset:2px}
</style>
"""

JS = """
<script>
document.querySelectorAll('.pcopy').forEach(function(b){
  b.addEventListener('click', function(){
    var pre = b.closest('.pblock').querySelector('pre');
    navigator.clipboard.writeText(pre.textContent).then(function(){
      var t = b.textContent; b.textContent = 'copied';
      setTimeout(function(){ b.textContent = t; }, 1200);
    });
  });
});
</script>
"""


def chip_class(tag):
    if tag.startswith(('@Room-', '@Motel-', '@House-', '@Bus-', '@Stop-')):
        return 'loc'
    if tag in ('@Mother', '@Mother-Soul', '@Daughter', '@Father'):
        return 'chr'
    return 'prp'


def main(target):
    src = open(PROMPTS).read()
    body = src.split('## The rule for every shot', 1)[1]
    blocks = re.split(r'\n## (?=Scene )', body)

    out = [BEGIN, CSS,
           '<div class="section-head">Prompt ทุกบล็อก '
           '<span class="upd new">New</span></div>',
           '<p class="section-sub">ตัวเต็มที่ operator ก๊อปไปวางตรง ๆ '
           'สร้างจาก <code>PROMPTS.md</code> อัตโนมัติ — '
           '<strong>ห้ามแก้ในหน้านี้</strong> แก้ที่ไฟล์แล้วสั่ง generate ใหม่ '
           'ไม่งั้นสองที่จะไม่ตรงกัน</p>']

    for b in blocks[1:]:
        title = b.split('\n', 1)[0].strip()
        code_m = re.findall(r'```(.*?)```', b, re.S)
        if not code_m:
            continue
        code = code_m[0].strip('\n')
        scene = title.split()[1].rstrip('—').strip()
        tags = sorted(set(TAG.findall(code)))
        frozen = scene.startswith(FROZEN_SCENES)

        chips = ''.join(
            f'<span class="pchip {chip_class(t)}">{html.escape(t)}</span>'
            for t in tags)

        cap = MAX_ELEMENTS_SEEDANCE_25 if 'Seedance 2.5' in title else MAX_ELEMENTS
        if frozen:
            badge = '<span class="pbadge frozen">frozen</span>'
        elif len(tags) > cap or (set(tags) & FORBIDDEN):
            badge = '<span class="pbadge frozen">check</span>'
        else:
            badge = '<span class="pbadge ok">ready</span>'

        note = ''
        if frozen:
            note = ('<div class="pnote">FROZEN — คลิปส่งแล้ว. '
                    'ห้ามเข้าคิวโดยไม่ถาม CEO ก่อน</div>')

        out.append(
            f'<div class="pblock">'
            f'<div class="pblock-head">'
            f'<span class="pblock-name">{html.escape(title)}</span>'
            f'{badge}{chips}'
            f'<span class="pblock-count">{len(tags)}/{cap}</span>'
            f'<button class="pcopy" type="button">copy</button>'
            f'</div>{note}<pre>{html.escape(code)}</pre></div>')

    out.append(JS)
    out.append(END)
    section = '\n'.join(out)

    page = open(target).read()
    if BEGIN in page and END in page:
        page = re.sub(re.escape(BEGIN) + r'.*?' + re.escape(END),
                      lambda _: section, page, flags=re.S)
    else:
        # First run. Land it above the footer - anchoring on the last closing
        # tag instead puts the whole section visually below the page footer.
        m = re.search(r'\n\s*<footer', page)
        anchor = m.start() if m else page.rindex('</div>')
        page = page[:anchor] + '\n' + section + '\n' + page[anchor:]

    open(target, 'w').write(page)
    n = section.count('<div class="pblock">')
    print(f'injected {n} prompt blocks into {target}')


if __name__ == '__main__':
    main(sys.argv[1])
